### ISSUE TITLE
403 error again

### ISSUE THREAD

**Issue by desbma** [Boudewijn26/gTTS-token#4]
Hi @Boudewijn26 

It looks like Google changed the token calculation code, I am getting 403 errors again while using gTTS-token.

Both GoogleSpeech and gTTS are affected (same errors).
For example: https://travis-ci.org/desbma/GoogleSpeech/jobs/130435066#L444

Can you please look at it?

Thanks

**Comment by Boudewijn26** [comment]
Hi @desbma,

Thanks for the heads up. I'll try to get on it later this week.

Google translate also uses a new url now, I'll report back to inform if the old url has been blocked. It does appear the change is rather small: the TKK has been changed to include another parameter. It's now the beautiful looking
`TKK=eval('((function(){var a\x3d3039855180;var b\x3d-1096878591;return 406547+\x27.\x27+(a+b)})())');`
Resulting in something like `406547.1942976589`. You may notice the `406547` still remains. This only thing that I see different in the algorithm is that near the end the token gets XOR-ed by the second part of the seed.

As I said, I'll get on this and report back.

Regards

**Comment by Boudewijn26** [comment]
By the way it appears that changing the client to tw-ob bypasses the entire token script.

[First suggested here.](http://stackoverflow.com/questions/32053442/google-translate-tts-api-blocked)

I'll continue maintaining this just for the fun of it (let's see how far Google takes this), but it appears that changing the client is the more robust option for now.

**Comment by desbma** [comment]
Interesting, thanks for the analysis.
It appears other values for `client` seem to work too.

I'll use this workaround for now, but I won't be surprised if they protect it more in the future and require the token for all clients. So please don't abandon the reverse engineering, it might be needed again soon. :)

It seems some Google engineers are hard at work trying to prevent us from making our computers speak !

**Comment by Boudewijn26** [comment]
I'm closing this issue as this has been fixed in the latest release (1.1.1) of gTTs-token.

This version has the unfortunate side effect of using an extra http request to get the second part of the TKK variable using by the script. 

The main issue is that the TKK variable now has two parts: the first one (this amount of hours since epoch) remains the same. However it is now followed by a dot and a number. This number is the sum of two other numbers as mentioned earlier. I'm currently running a script which pings Google's server every 30 seconds in order to collect as many of these as possible and maybe find a pattern in them. It appears these numbers change every minute or so.

It also includes a real life test, which has the minimal amount of parameters needed to get a valid response. All of this can be seen in this [commit](https://github.com/Boudewijn26/gTTS-token/commit/04721997a2f3b568d0a8ba127b479441c7d6776a).

Once I gathered enough data, I'll post them to pastebin and see if we can crowdsource this problem.
